# Generated by Django 5.2.1 on 2025-09-05 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacante',
            name='nombre_interno',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
