# Generated by Django 4.2.23 on 2025-10-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='resumen_ia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='score_ia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacante',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
