# Generated by Django 4.2.23 on 2025-10-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_postulacion_resumen_ia_postulacion_score_ia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postulacion',
            options={'ordering': ['-score_ia', '-fecha_postulacion']},
        ),
        migrations.RemoveField(
            model_name='postulacion',
            name='resumen_ia',
        ),
        migrations.RemoveField(
            model_name='vacante',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='postulacion',
            name='razon_ia',
            field=models.TextField(blank=True, help_text='Razón del score generada por IA', null=True),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='score_ia',
            field=models.IntegerField(blank=True, help_text='Score de 0-100 generado por IA', null=True),
        ),
    ]
