# Generated by Django 4.2.23 on 2025-10-15 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0006_alter_postulacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('REVISADO', 'Revisado'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='notas_reclutador',
            field=models.TextField(blank=True, help_text='Notas del reclutador', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='postulacion',
            unique_together={('postulante', 'vacante')},
        ),
    ]
